version: 2.1
orbs:
  eventuate-gradle-build-and-test: eventuate_io/eventuate-gradle-build-and-test@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - eventuate-gradle-build-and-test/build-and-test:
          name: test-build-and-test
          project_name: test-orb
          script: ./build-and-test-all-example.sh
          filters: *filters
      - eventuate-gradle-build-and-test/build-and-test:
          name: test-build-and-test-arm
          machine_image: ubuntu-2004:current
          resource_class: arm.large
          project_name: test-orb
          script: SOME_ENV_VAR=xxx ./build-and-test-all-example.sh
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: eventuate_io/eventuate-gradle-build-and-test
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - test-build-and-test
            - test-build-and-test-arm
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
